import { expect, test } from "@playwright/test";
import "../apps/web/src/debug";

test("work tiles, collect resources, grow population and upgrade Town Hall", async ({ page }, testInfo) => {
  await page.goto("/");
  await page.waitForFunction(() => !!window.__GAME_DEBUG__);
  await page.evaluate(() => window.__GAME_DEBUG__!.setSeed("fern-104"));
  const selectCity = async () => {
    const point = await page.evaluate(() => window.__GAME_DEBUG__!.getUnitScreenPosition("warrior-1"));
    await page.mouse.click(point.x, point.y);
    await expect(page.getByTestId("population")).toBeVisible();
    await page.getByRole("button", { name: "Manage resources", exact: true }).click();
  };
  await selectCity();
  await expect(page.getByTestId("population")).toHaveText("3 / 5");
  await expect(page.getByText("Civilians / military")).toBeVisible();
  const tile = async (x: number, y: number) => {
    const point = await page.evaluate(({ x, y }) => window.__GAME_DEBUG__!.getTileScreenPosition(x, y), { x, y });
    await page.mouse.click(point.x, point.y);
    await expect(page.getByRole("region", { name: "Resource tile", exact: true })).toBeVisible();
  };
  await tile(4, 3);
  await page.getByRole("button", { name: "Assign Civilian", exact: true }).click();
  expect(await page.evaluate(() => window.__GAME_DEBUG__!.getState().cities[0].workedTiles)).toEqual(["4,3"]);
  await tile(4, 4);
  await page.getByRole("button", { name: "Assign Civilian", exact: true }).click();
  const turn = page.getByRole("button", { name: "End Turn", exact: true });
  await turn.click();
  await turn.click();
  await selectCity();
  await expect(page.getByTestId("food")).toContainText("3");
  await expect(page.getByTestId("wood")).toContainText("2");
  await turn.click();
  await turn.click();
  await selectCity();
  await page.getByRole("button", { name: "Grow Population" }).click();
  await expect(page.getByTestId("population")).toHaveText("4 / 5");
  await page.getByRole("button", { name: "Upgrade Town Hall" }).click();
  await expect(page.getByTestId("population")).toHaveText("4 / 8");
  await expect(page.getByTestId("town-hall")).toHaveText("2 / 3");
  const state = await page.evaluate(() => window.__GAME_DEBUG__!.getState());
  expect(state.players[0].resources).toEqual({ gold: 2, food: 2, wood: 4, steel: 0 });
  expect(state.units[0]).toMatchObject({ homeCityId: "city-1", populationCost: 1 });
  await tile(4, 3);
  await page.getByRole("button", { name: "Unassign Civilian", exact: true }).click();
  expect(await page.evaluate(() => window.__GAME_DEBUG__!.getState().cities[0].workedTiles)).toEqual(["4,4"]);
  await turn.click();
  await turn.click();
  const produced = await page.evaluate(() => window.__GAME_DEBUG__!.getState().players[0].resources);
  expect(produced).toEqual({ gold: 5, food: 2, wood: 6, steel: 0 });
  await selectCity();
  await page.screenshot({ path: testInfo.outputPath("city-economy.png") });
});
